In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
type(mylist)

list

In [6]:
my_matrix= [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0 ,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [11]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(5,2)

array([[0.69106072, 0.86366545],
       [0.81790675, 0.37826803],
       [0.46704479, 0.14643328],
       [0.24107368, 0.19551317],
       [0.59504101, 0.14682311]])

In [19]:
np.random.randn(2,3)

array([[ 0.32351757, -0.04952206,  0.90153861],
       [-1.06219305, -0.47427794, -0.2728954 ]])

In [34]:
np.random.randint(0, 101, (2,5))

array([[74, 65, 92, 43, 42],
       [10, 93, 89, 63, 74]])

In [20]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [32]:
arr = np.arange(0 ,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr = np.random.randint(0, 101, 10)

In [39]:
ranarr.max()

99

In [40]:
ranarr.min()

2

In [42]:
ranarr.argmax()

5

In [43]:
ranarr.argmin()

7

In [45]:
ranarr.dtype

dtype('int32')

In [46]:
arr.shape


(25,)

In [47]:
arr = arr.reshape(5,5)

In [48]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr.shape

(5, 5)