In [2]:
import numpy as np 

In [3]:

a1 = np.array([1,2,3,])

In [4]:
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.5]]
             )
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1)

numpy.ndarray

In [16]:
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int32')

In [19]:
ones = np.ones((2,3))

In [20]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeroes = np.zeros((2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0, 10, 2)

In [25]:
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0, 10, size=(3,5))

In [27]:
random_array

array([[4, 0, 7, 5, 6],
       [2, 0, 5, 7, 9],
       [0, 0, 7, 6, 9]])

In [29]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.77264551, 0.65136477, 0.19026007],
       [0.02269362, 0.81620656, 0.31059326],
       [0.10611804, 0.78286631, 0.16186187],
       [0.10270007, 0.22332391, 0.09129315],
       [0.4479458 , 0.53677887, 0.481019  ]])

In [30]:
radnom_array_2.shape

(5, 3)

In [32]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.39582462, 0.78742951, 0.8941309 ],
       [0.76199799, 0.25739764, 0.74828025],
       [0.41129871, 0.21643561, 0.72310521],
       [0.53524242, 0.27417454, 0.06381789],
       [0.42537833, 0.73675645, 0.17151757]])

In [38]:
np.random.seed(0)
random_aaray_4 = np.random.randint(10, size=(5,3))
random_aaray_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [36]:
random_aaray_4.shape

(5, 3)

3. Viewing and Matrices

In [39]:
np.unique(random_aaray_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a1

array([1, 2, 3])

In [41]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [43]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [44]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [46]:
a4[:, :, :, :4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

In [48]:
a1

array([1, 2, 3])

In [49]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [50]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [51]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [55]:
a1

array([1, 2, 3])

In [53]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [59]:
a2.shape

(2, 3)

In [61]:
a2_3d = a2.reshape(2,3,-1)

In [62]:
a2_3d.shape, a2_3d

((2, 3, 1),
 array([[[1. ],
         [2. ],
         [3.3]],
 
        [[4. ],
         [5. ],
         [6.5]]]))

In [63]:
a3 * a2_3d

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [66]:
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [67]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [68]:
listy_list = [1,2,3]

In [69]:
type(listy_list)

list

In [70]:
sum(listy_list)

6

In [71]:
type(a1)

numpy.ndarray

In [72]:
a1.sum()

6

In [73]:
massive_array = np.random.random(100000)

In [75]:
massive_array[:10]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [85]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

14 ms ± 1.84 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
55.4 µs ± 5.75 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [78]:
np.mean(a2)

3.6333333333333333

In [81]:
np.max(a2)

6.5

In [82]:
np.min(a2)

1.0

In [83]:
np.std(a2)

1.8226964152656422

In [84]:
np.var(a2)

3.3222222222222224

In [86]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [87]:
a2.shape

(2, 3)

In [88]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [89]:
a3.shape

(2, 3, 3)

In [90]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [91]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [93]:
a2.shape

(2, 3)

In [94]:
a2_3d * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [95]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [96]:
a2.shape

(2, 3)

In [97]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [98]:
a2.T.shape

(3, 2)

In [99]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))
mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [100]:
mat1* mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [102]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [103]:
mat1.T.shape

(3, 5)

In [105]:
mat2.shape

(5, 3)

In [106]:
mat3 = np.dot(mat1, mat2.T)

In [107]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [108]:
mat3.shape

(5, 5)

In [111]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [112]:
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", "Wed", "Thu", "Fri"], columns=["Almond butter", "Peanut butter", "Cashew Butter"])

In [113]:
weekly_sales

Almond butter  Peanut butter  Cashew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thu               4              6             12
Fri               1              6              7

In [114]:
ptice = np.array([10, 8, 12])

In [116]:
butter_prices = pd.DataFrame(ptice.reshape(1,3), index=["Price"], columns=["Almond butter", "Peanut butter", "Cashew Butter"])

In [117]:
butter_prices

Almond butter  Peanut butter  Cashew Butter
Price             10              8             12

In [118]:
total_sales = ptice.dot(sales_amounts.T)

In [119]:
total_sales

array([240, 138, 458, 232, 142])

In [120]:
weekly_sales

Almond butter  Peanut butter  Cashew Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thu               4              6             12
Fri               1              6              7

In [122]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [123]:
weekly_sales["Total $"] = daily_sales.T
weekly_sales 

Almond butter  Peanut butter  Cashew Butter  Total $
Mon              12             15              0      240
Tues              3              3              7      138
Wed               9             19             18      458
Thu               4              6             12      232
Fri               1              6              7      142

In [124]:
a1

array([1, 2, 3])

In [125]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [126]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [127]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [128]:
random_array

array([[4, 0, 7, 5, 6],
       [2, 0, 5, 7, 9],
       [0, 0, 7, 6, 9]])

In [130]:
np.sort(random_array)

array([[0, 4, 5, 6, 7],
       [0, 2, 5, 7, 9],
       [0, 0, 6, 7, 9]])

In [131]:
np.argsort(random_array)

array([[1, 0, 3, 4, 2],
       [1, 0, 2, 3, 4],
       [0, 1, 3, 2, 4]], dtype=int64)

In [132]:
np.argmin(a1)

0

In [133]:
np.argmax(a2)

5

In [134]:
np.argmax(random_array, axis=0)

array([0, 0, 0, 1, 1], dtype=int64)

In [136]:
%matplotlib inline

In [139]:
from matplotlib.image import imread

panda = imread("./images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [140]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [141]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [142]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

In [143]:
car = imread("./images/car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [144]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

In [145]:
dog = imread("images/dog-photo.png")

In [146]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [147]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)